import type { EnemyVisual } from './types';
import { drawBlob } from './blob';
import { drawFly } from './fly';
import { drawWalker } from './walker';
import { drawShooter } from './shooter';
import { drawCharger } from './charger';
import { drawRotling } from './rotling';
import { drawSpitter } from './spitter';
import { drawChiller } from './chiller';
import { drawLancer } from './lancer';
import { drawPyro } from './pyro';
import { drawBombardier } from './bombardier';
import { drawMistweaver } from './mistweaver';
import { drawRoach } from './roach';
import { drawSpider } from './spider';
import { drawTick } from './tick';
import { drawSniper } from './sniper';
import { drawMortar } from './mortar';
import { drawSummoner } from './summoner';
import { drawStriker } from './striker';
import { drawWorm } from './worm';
import { drawShotgunner } from './shotgunner';
import { drawGunner } from './gunner';
import { drawBlinker } from './blinker';
import { drawConfuser } from './confuser';
import { drawBlocker } from './blocker';
import { drawLeaper } from './leaper';
import { drawFlanker } from './flanker';
import { drawHealer } from './healer';
import { drawEnrager } from './enrager';
import { drawKamikaze } from './kamikaze';
import { drawSlammer } from './slammer';
import { drawTurret } from './turret';
import { drawGasbag } from './gasbag';
import { drawPuller } from './puller';
import { drawBombthrower } from './bombthrower';
import { drawMinotaur } from './minotaur';
import { drawMummy } from './mummy';
import { drawScarab } from './scarab';
import { drawVampire } from './vampire';
import { drawBat } from './bat';
import { drawLeech } from './leech';
import { drawSerpent } from './serpent';
import { drawMedusa } from './medusa';
import { drawSkeleton } from './skeleton';
import { drawWraith } from './wraith';
import { drawGargoyle } from './gargoyle';
import { drawHarpy } from './harpy';
import { drawCyclops } from './cyclops';
import { drawGolem } from './golem';
import { drawScorpion } from './scorpion';
import { drawWisp } from './wisp';
import { drawBanshee } from './banshee';
import { drawImp } from './imp';
import { drawHydra } from './hydra';
import { drawWerewolf } from './werewolf';
import { drawBossBeast } from './bossBeast';

export type { EnemyVisual };

export function drawEnemy(ctx: CanvasRenderingContext2D, v: EnemyVisual): void {
  switch (v.kind) {
    case 'fly': return drawFly(ctx, v);
    case 'walker': return drawWalker(ctx, v);
    case 'shooter': return drawShooter(ctx, v);
    case 'charger': return drawCharger(ctx, v);
    case 'rotling': return drawRotling(ctx, v);
    case 'spitter': return drawSpitter(ctx, v);
    case 'chiller': return drawChiller(ctx, v);
    case 'lancer': return drawLancer(ctx, v);
    case 'pyro': return drawPyro(ctx, v);
    case 'bombardier': return drawBombardier(ctx, v);
    case 'mistweaver': return drawMistweaver(ctx, v);
    case 'roach': return drawRoach(ctx, v);
    case 'spider': return drawSpider(ctx, v);
    case 'spiderling': return drawSpider(ctx, v);
    case 'tick': return drawTick(ctx, v);
    case 'sniper': return drawSniper(ctx, v);
    case 'mortar': return drawMortar(ctx, v);
    case 'summoner': return drawSummoner(ctx, v);
    case 'striker': return drawStriker(ctx, v);
    case 'worm': return drawWorm(ctx, v);
    case 'shotgunner': return drawShotgunner(ctx, v);
    case 'gunner': return drawGunner(ctx, v);
    case 'blinker': return drawBlinker(ctx, v);
    case 'confuser': return drawConfuser(ctx, v);
    case 'blocker': return drawBlocker(ctx, v);
    case 'leaper': return drawLeaper(ctx, v);
    case 'flanker': return drawFlanker(ctx, v);
    case 'healer': return drawHealer(ctx, v);
    case 'enrager': return drawEnrager(ctx, v);
    case 'kamikaze': return drawKamikaze(ctx, v);
    case 'slammer': return drawSlammer(ctx, v);
    case 'turret': return drawTurret(ctx, v);
    case 'gasbag': return drawGasbag(ctx, v);
    case 'puller': return drawPuller(ctx, v);
    case 'bombthrower': return drawBombthrower(ctx, v);
    case 'minotaur': return drawMinotaur(ctx, v);
    case 'mummy': return drawMummy(ctx, v);
    case 'scarab': return drawScarab(ctx, v);
    case 'vampire': return drawVampire(ctx, v);
    case 'bat': return drawBat(ctx, v);
    case 'leech': return drawLeech(ctx, v);
    case 'serpent': return drawSerpent(ctx, v);
    case 'medusa': return drawMedusa(ctx, v);
    case 'skeleton': return drawSkeleton(ctx, v);
    case 'wraith': return drawWraith(ctx, v);
    case 'gargoyle': return drawGargoyle(ctx, v);
    case 'harpy': return drawHarpy(ctx, v);
    case 'cyclops': return drawCyclops(ctx, v);
    case 'golem': return drawGolem(ctx, v);
    case 'scorpion': return drawScorpion(ctx, v);
    case 'wisp': return drawWisp(ctx, v);
    case 'banshee': return drawBanshee(ctx, v);
    case 'imp': return drawImp(ctx, v);
    case 'hydra': return drawHydra(ctx, v);
    case 'werewolf': return drawWerewolf(ctx, v);
    case 'boss':
    case 'boss3':
      return drawBossBeast(ctx, v);
    default: return drawBlob(ctx, v);
  }
}
